In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler
import theano
import tensorflow
import keras
from sklearn.linear_model import LogisticRegression
import sys
from sklearn.metrics import confusion_matrix, accuracy_score
from keras.models import Sequential
from keras.layers import Dense
import pickle
import os
from sklearn.metrics import accuracy_score

In [2]:
print('version of theano : ', theano.__version__)
print('version of tensorflow : ', tensorflow.__version__)
print('version of keras : ', keras.__version__)


version of theano :  1.0.5
version of tensorflow :  2.3.0
version of keras :  2.4.3


In [3]:
df = pd.read_csv(r'https://raw.githubusercontent.com/aniruddhgoteti/Bank-Customer-Churn-Modelling/master/data.csv.csv')

In [4]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [6]:
X=df.iloc[:, 3:13]
X.columns

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary'],
      dtype='object')

In [7]:
import json
columns = {'data_columns' : [col.lower() for col in X.columns]}

with open("columns.json","w") as f:
    f.write(json.dumps(columns))   

In [8]:
X=df.iloc[:, 3:13].values
X.shape
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [9]:
y=df.iloc[:,-1].values
y.shape
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [10]:
print(X[:,1])
print(X[:,2])

['France' 'Spain' 'France' ... 'France' 'Germany' 'France']
['Female' 'Female' 'Female' ... 'Female' 'Male' 'Female']


In [11]:
le=LabelEncoder()
X[:,1]=le.fit_transform(X[:,1])
le_2=LabelEncoder()
X[:,2]=le_2.fit_transform(X[:,2])

In [12]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2)

In [13]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(8000, 10) (2000, 10) (8000,) (2000,)


In [14]:
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.fit_transform(X_test)

In [15]:
classifier=LogisticRegression()

In [16]:
X_train.ndim

2

In [17]:
classifier.fit(X_train, y_train)

LogisticRegression()

In [18]:
y_pred = classifier.predict(X_test)

In [19]:
np.set_printoptions(threshold=sys.maxsize)
print(y_pred.shape)
print(y_pred[25])
print(X_test[25])

(2000,)
0
[ 0.46865518 -0.89813026  0.90911166 -0.35621031 -0.01372559  0.92037201
 -0.92250216  0.62593007 -1.02020406 -0.62535134]


In [20]:
cm= confusion_matrix(y_test,y_pred)
cm

array([[1542,   46],
       [ 332,   80]], dtype=int64)

In [21]:
print(cm)
print("Accuracy =")
print((1566+68)/2000)

[[1542   46]
 [ 332   80]]
Accuracy =
0.817


## Go ANN!

In [22]:
clr= Sequential()
clr.add(Dense(units=6, kernel_initializer="uniform", activation= "relu", input_dim=10))
clr.add(Dense(units=6, kernel_initializer="uniform", activation= "relu"))
clr.add(Dense(units=1, kernel_initializer="uniform", activation= "sigmoid"))

In [23]:
#if more than one dependant variables, use Softmax and make output dim as no of dependant varibles
#also use performance tuning
#more than one dependant othr loss function
clr.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [24]:
clr.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
800/800 [==============================] - 1s 775us/step - loss: 0.4921 - accuracy: 0.7970
Epoch 2/100
800/800 [==============================] - 1s 693us/step - loss: 0.4322 - accuracy: 0.7969
Epoch 3/100
800/800 [==============================] - 1s 736us/step - loss: 0.4286 - accuracy: 0.7969
Epoch 4/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4238 - accuracy: 0.8135
Epoch 5/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4180 - accuracy: 0.8257: 0s -
Epoch 6/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4122 - accuracy: 0.8326
Epoch 7/100
800/800 [==============================] - 1s 1ms/step - loss: 0.4087 - accuracy: 0.8361
Epoch 8/100
800/800 [==============================] - 1s 854us/step - loss: 0.4054 - accuracy: 0.8357
Epoch 9/100
800/800 [==============================] - 1s 779us/step - loss: 0.4037 - accuracy: 0.8359
Epoch 10/100
800/800 [==============================] - 1s 884us/step - los

800/800 [==============================] - 1s 976us/step - loss: 0.3895 - accuracy: 0.8415
Epoch 80/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3893 - accuracy: 0.8406
Epoch 81/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3899 - accuracy: 0.8420
Epoch 82/100
800/800 [==============================] - 1s 966us/step - loss: 0.3899 - accuracy: 0.8399
Epoch 83/100
800/800 [==============================] - 1s 895us/step - loss: 0.3895 - accuracy: 0.8406
Epoch 84/100
800/800 [==============================] - 1s 870us/step - loss: 0.3891 - accuracy: 0.8430
Epoch 85/100
800/800 [==============================] - 1s 967us/step - loss: 0.3896 - accuracy: 0.8414
Epoch 86/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3899 - accuracy: 0.8401
Epoch 87/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3896 - accuracy: 0.8421
Epoch 88/100
800/800 [==============================] - 1s 1ms/step - loss: 0.3898 - 

In [25]:
y_pred = np.around(clr.predict(X_test), 0).flatten()

In [26]:
y_pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0.

In [27]:
accuracy_score(y_test, y_pred)

0.825

In [28]:
cm= confusion_matrix(y_test,y_pred)
cm

array([[1519,   69],
       [ 281,  131]], dtype=int64)

In [29]:
100*(1538+173)/2000

85.55

In [30]:
print(y_test[1])
print(y_pred[1])
print(X_test[1])
print(X_test.ndim)
print(X_test[1].ndim)

0
0.0
[-0.92654592  1.53417918 -1.09997489 -0.73652292 -0.01372559  0.79617277
 -0.92250216  0.62593007 -1.02020406 -0.37058573]
2
1


In [31]:
yy1 = np.around(clr.predict([[-1.30362717,  0.28261018,  0.87833888,  0.23127098, -1.7704396,   0.68029117,
 -0.92465267, -1.59959959, -1.04920939,  0.31467593]]))
yy1

array([[0.]], dtype=float32)

In [32]:
from tensorflow.keras.models import load_model

clr.save('model_resnet50.h5')

In [33]:
keras.__version__

'2.4.3'